add missing deps in compiler target (#328)
The following error when building was reported
```
.../iree-amd-aie/compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp:28:10: fatal error: 'runtime/plugins/AMD-AIE/iree-amd-aie/schemas/xrt_executable_def_builder.h' file not found
   28 | #include "runtime/plugins/AMD-AIE/iree-amd-aie/schemas/xrt_executable_def_builder.h"
 ```
 Adding this deps should fix that.