[LowerToAIE] fix for `op could not fold repetition counts` (#1055)
This is a fix for the compilation error
```
<unknown>:0: error: 'amdaie.npu.circular_dma_cpy_nd' op could not fold repetition counts
```

that is observed some transposed matmuls with the new pack-peel
pipeline. What was happening was that the `lower-to-aie` pass is assumed
a stride-0 leading dimension was always or never present, but that
wasn't the case