[CreateLogicalObjectFifoLink] Fail if accesses not contiguous  (#696)
I was looking into this pass because convolution lowering hits 

```
error: 'amdaie.circular_dma_cpy_nd' op access pattern of strided operation overlaps with next one, which is not supported for now
```

But looking at the code now, it looks like it'll currently only work for
the the access patterns are perfectly contiguous? If that's the case, I
can look into fixing it (for both cases -- overlapping and
non-contiguous).

I left a comment in the code describing my thinking